name: myco16
description: MYCO-16, sampler de poche Android (prototype).
publish_to: 'none'
version: 0.4.0+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_soloud: ^5.0.0
  record: ^6.0.0
  path_provider: ^2.1.0

flutter:
  uses-material-design: true
